# Generated by Django 5.0.7 on 2024-07-11 19:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=255)),
                ('plate', models.CharField(max_length=6)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
