# Generated by Django 5.0.7 on 2024-07-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
