# Generated by Django 5.0.7 on 2024-07-14 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('trip', '0002_trip_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destiny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_destiny', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_origin', to='branch.branch'),
        ),
    ]
