# Generated by Django 5.0.7 on 2024-07-15 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='adress',
            new_name='address',
        ),
    ]
